#  bot API token with "bot" being first 3 characters
bot-token: <bot-token>
# timeout in seconds for the long pulling
pull-timeout: 30
# timeout in seconds for bot to decide kicking a newly added member
kick-timeout: 600
# a file path for log output
log-file: <path-to-log-file>
# a file path for storing bot state (don't have to actually present upon startup)
state-file: <path-to-state-file>
# fileId of stickers
whale-stickers: []
# chatId of groups that the bot should respond to
watching-groups: []
