# timeout in seconds for bot to decide kicking a newly added member
kick-timeout: 600
# timeout in seconds for the long pulling
pull-timeout: 30
# a file path for storing bot state (don't have to actually present upon startup)
state-file: <path-to-state-file>
# a file path for log output
log-file: <path-to-log-file>
# bot API token with "bot" being first 3 characters
bot-token: <bot-token>
# user id of the bot, can use -1 if don't know
self-user-id: -1
# chatId of groups that the bot should respond to
watching-groups: []
# fileId of stickers
whale-stickers: []
# repeat cooldown in seconds
repeat-cooldown: 30
# watching window of the repeater in seconds
repeat-window: 300
# how many unique, non-bot user should trigger the repeater
repeat-uniq-user-count: 3