name: whale-of-whales
version: 0.1.0.0
homepage: https://github.com/githubuser/whale-of-whales#readme
maintainer: Javran Cheng <Javran.C@gmail.com>
github: Javran/whale-of-whales
extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall -O2

executables:
  wow:
    main: Javran/Wow/Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Javran.Wow.Main
    other-modules:
    - Javran.Wow.Types
    - Javran.Wow.Base
    - Javran.Wow.Default
    - Javran.Wow.Util
    - Javran.Wow.ProcessUpdate
    - Javran.Wow.BotModule.UserVerification
    - Javran.Wow.BotModule.SendWhale
    - Javran.Wow.BotModule.SendYesOrNo
    - Javran.Wow.BotModule.Lmgtfy
    - Javran.Wow.BotModule.Chiba
    - Javran.Wow.BotModule.SimpleRandom
    - Javran.Wow.BotModule.CommandSink
    - Javran.Wow.BotModule.BianTaiXue
    - Javran.Wow.BotModule.Repeater
    dependencies:
    - base
    - telegram-api
    - http-client
    - http-client-tls
    - time
    - mtl
    - exceptions
    - servant-client
    - text
    - random
    - data-default-class
    - containers
    - aeson
    - yaml
    - uri-encode
