#!/bin/sh

# bot token should a string beginning with "bot"
export BOT_TOKEN=your_bot_token_here
export PULL_TIMEOUT=time_in_sec
export KICK_TIMEOUT=time_in_sec
export ERR_FILE=file_path
export STATE_FILE=file_path
export WATCHING_GROUPS=groups_separated_by_comma

stack build && stack exec -- wow
